Title: Automating Your Own Process
Author: David M. Bradford
css: table.css
Base Header Level:  2

Automating Your Own Process
===========================

DESCRIPTION
-----------
Although we as technical people often spend our lives automating things, we often neglect our own processes, frequently repeating steps that we could easily automate. We will discuss identifying repetetive tasks and different methods of automating them.

ABSTRACT
--------
Examining our own processes for needless repetition and then eliminating that repetition can be a huge productivity boon. My aim is to cast a wide net and discuss a wide range of technologies to get you thinking about your own process and steps you might take to streamline it. In addition I will review at least one practical use of each technology.

* The zen of identifying repetition
* Arguments against automation
    * Too many targets
    * "It's just one keystroke"
* Automation tools
    * Automation in the Unix shell
        * Command line history editing and shortcuts
        * Scripts
        * Aliases
    * vim macros
    * Browser extensions for automation
        * Stylish
        * Greasemonkey / Tampermonkey
    * autokey and other macro solutions
* How to affect change
    * incremental approach
* caveats
    * securing "destructive" shortcuts


