Title: TEMPLATE_TITLE1
Author: David M. Bradford
css: table.css
Base Header Level:  2

The purpose of this one is to talk about how I started to come out of my shell just recently and try to convince others to do the same.
* your perspective is valuable
* your responsibility to the community

Normal text with some `code`.

    print "a block of code";
    print "indent with spaces";

   A       | Dang         | Table
  -------- | ------------ | -------------------------------------------
   1       | `formatted`  | whatever
   2       | `code`       | blah blah

This is a link [Nice Text](http://actual.uri.com)

A link to an image:

![](fix_lines.gif)

