Title: Call for Contributors to Open Source Project "CLPM"
Author: David M. Bradford
css: table.css
Base Header Level:  2

[CLPM](https://github.com/tinypigdotcom/clpm) is my "Command Line Project Manager". It's a tool I wrote and have been using myself for several years now, and I am releasing it in the hope that others might find it useful.

Also, if you have been looking for an open source project to contribute to, here's your chance! I don't care what your level of experience is, if you think you have a useful comment or contribution, I'd like to hear from you!

There is a [Todo](https://github.com/tinypigdotcom/clpm#todo) section in the README, but I want to add a couple notes here:

1. It's currently not packaged, nor does it have an installer. This probably makes it much less likely to be adopted.
1. I'm not sure how to promote it to make sure its audience (developers/sysadmins maybe) at least get a chance to see it, even if it ends up that it's useful to nobody but me.

Project page w/`README.md`: https://github.com/tinypigdotcom/clpm

