Title: TEMPLATE_TITLE1
Author: David M. Bradford
css: table.css
Base Header Level:  2

The point of this article is to describe how to build a memory palace

* my travel example, spanish class mention
* our house + pi
* RAM refresh
* sleep help vs counting sheep
* standing in line or other boring times
* short term vs long term = I don't do long term
* increase absurdity to increase memory

http://en.wikipedia.org/wiki/Method_of_loci

Method of loci
From Wikipedia, the free encyclopedia
The Method of loci (loci being Latin for "places"[1]), also called the memory palace or mind palace

Normal text with some `code`.

    print "a block of code";
    print "indent with spaces";

   A       | Dang         | Table
  -------- | ------------ | -------------------------------------------
   1       | `formatted`  | whatever
   2       | `code`       | blah blah

This is a link [Nice Text](http://actual.uri.com)

A link to an image:

![](fix_lines.gif)

