Title: My Bad Communication Skills
Author: David M. Bradford
css: table.css
Base Header Level:  2

A couple weeks ago I asked how you "[join the conversation](http://tinypig2.blogspot.com/2015/02/how-do-you-join-conversation.html)" but based on feedback I got, I don't think I communicated well.  I think people thought I meant "which blogs do you read?" What I really meant was: when you *write* a blog entry, where do you post the link so that it's seen by people who are interested in that subject?

So for example, when I write about Perl, I post to blogs.perl.org.  I want to blog about other topics too, like web development (JavaScript, CSS, etc); lifehacks; Unix, Linux, shell scripting; general tech / tech business; and database stuff.  But when I blog I'd like it to have a chance of being seen. Please let me know your thoughts!

