Title: My Debug Snippet for mod_perl
Author: David M. Bradford
css: table.css
Base Header Level:  2

These days I find myself working on mod_perl apps. Though I would sometimes prefer a different tool, `print` has been very reliable for me. I've found it useful to create a snippet for myself that I can paste when I need to see what's going on in the application.

    use IO::File;
    use Data::Dumper;
    my %dmb;
    $dmb{outfile} = '/tmp/dmb.out';
    $dmb{oh} = IO::File->new($dmb{outfile}, '>>');
    $dmb{mode} = 0666; chmod $dmb{mode}, $dmb{outfile};
    $dmb{st} = 0;
    $dmb{st}++ if defined $dmb{oh};
    $dmb{file} = __FILE__; $dmb{file} =~ s{.*/}{};
    print { $dmb{oh} } localtime . " $dmb{file}:" . __LINE__ . ':' . Dumper('WHATEVER') . "\n" if $dmb{st};
    # CLOSE!!
    # $dmb{oh}->close if $dmb{st};

